# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reports.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "optics_agent.proto.Id128" do
    optional :high, :sfixed64, 1
    optional :low, :sfixed64, 2
  end
  add_message "optics_agent.proto.Timestamp" do
    optional :seconds, :int64, 1
    optional :nanos, :int32, 2
  end
  add_message "optics_agent.proto.Error" do
    optional :message, :string, 1
  end
  add_message "optics_agent.proto.Trace" do
    optional :server_id, :message, 1, "optics_agent.proto.Id128"
    optional :client_id, :message, 2, "optics_agent.proto.Id128"
    optional :start_time, :message, 4, "optics_agent.proto.Timestamp"
    optional :signature, :string, 5
    optional :details, :message, 6, "optics_agent.proto.Trace.Details"
    optional :client_name, :string, 7
    optional :client_version, :string, 8
    optional :client_address, :string, 9
    optional :http, :message, 10, "optics_agent.proto.Trace.HTTPInfo"
    optional :parse, :message, 12, "optics_agent.proto.Trace.Node"
    optional :validate, :message, 13, "optics_agent.proto.Trace.Node"
    optional :execute, :message, 14, "optics_agent.proto.Trace.Node"
  end
  add_message "optics_agent.proto.Trace.Details" do
    map :variables, :string, :bytes, 1
    optional :raw_query, :string, 2
    optional :operation_name, :string, 3
  end
  add_message "optics_agent.proto.Trace.HTTPInfo" do
    optional :method, :enum, 1, "optics_agent.proto.Trace.HTTPInfo.Method"
    optional :host, :string, 2
    optional :path, :string, 3
    map :headers, :string, :string, 4
    optional :secure, :bool, 8
    optional :protocol, :string, 9
  end
  add_enum "optics_agent.proto.Trace.HTTPInfo.Method" do
    value :UNKNOWN, 0
    value :OPTIONS, 1
    value :GET, 2
    value :HEAD, 3
    value :POST, 4
    value :PUT, 5
    value :DELETE, 6
    value :TRACE, 7
    value :CONNECT, 8
    value :PATCH, 9
  end
  add_message "optics_agent.proto.Trace.Node" do
    optional :type, :string, 3
    optional :alias, :string, 4
    optional :start_time, :uint64, 8
    optional :end_time, :uint64, 9
    repeated :error, :message, 11, "optics_agent.proto.Error"
    repeated :child, :message, 12, "optics_agent.proto.Trace.Node"
    oneof :id do
      optional :field_name, :string, 1
      optional :index, :uint32, 2
    end
  end
  add_message "optics_agent.proto.ReportHeader" do
    optional :service, :string, 3
    optional :hostname, :string, 5
    optional :agent_version, :string, 6
    optional :service_version, :string, 7
    optional :runtime_version, :string, 8
    optional :uname, :string, 9
  end
  add_message "optics_agent.proto.StatsPerClientName" do
    repeated :latency_count, :uint64, 1
    repeated :error_count, :uint64, 2
    map :count_per_version, :string, :uint64, 3
  end
  add_message "optics_agent.proto.FieldStat" do
    optional :name, :string, 2
    optional :returnType, :string, 3
    repeated :latency_count, :uint64, 8
  end
  add_message "optics_agent.proto.TypeStat" do
    optional :name, :string, 1
    repeated :field, :message, 2, "optics_agent.proto.FieldStat"
  end
  add_message "optics_agent.proto.StatsPerSignature" do
    map :per_client_name, :string, :message, 1, "optics_agent.proto.StatsPerClientName"
    repeated :per_type, :message, 2, "optics_agent.proto.TypeStat"
  end
  add_message "optics_agent.proto.TracesReport" do
    optional :header, :message, 1, "optics_agent.proto.ReportHeader"
    repeated :trace, :message, 2, "optics_agent.proto.Trace"
  end
  add_message "optics_agent.proto.Field" do
    optional :name, :string, 2
    optional :returnType, :string, 3
  end
  add_message "optics_agent.proto.Type" do
    optional :name, :string, 1
    repeated :field, :message, 2, "optics_agent.proto.Field"
  end
  add_message "optics_agent.proto.StatsReport" do
    optional :header, :message, 1, "optics_agent.proto.ReportHeader"
    optional :start_time, :message, 8, "optics_agent.proto.Timestamp"
    optional :end_time, :message, 9, "optics_agent.proto.Timestamp"
    optional :realtime_duration, :uint64, 10
    map :per_signature, :string, :message, 12, "optics_agent.proto.StatsPerSignature"
    repeated :type, :message, 13, "optics_agent.proto.Type"
  end
  add_message "optics_agent.proto.SchemaReport" do
    optional :header, :message, 1, "optics_agent.proto.ReportHeader"
    optional :introspection_result, :string, 8
    repeated :type, :message, 9, "optics_agent.proto.Type"
  end
end

module OpticsAgent
  module Proto
    Id128 = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.Id128").msgclass
    Timestamp = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.Timestamp").msgclass
    Error = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.Error").msgclass
    Trace = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.Trace").msgclass
    Trace::Details = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.Trace.Details").msgclass
    Trace::HTTPInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.Trace.HTTPInfo").msgclass
    Trace::HTTPInfo::Method = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.Trace.HTTPInfo.Method").enummodule
    Trace::Node = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.Trace.Node").msgclass
    ReportHeader = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.ReportHeader").msgclass
    StatsPerClientName = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.StatsPerClientName").msgclass
    FieldStat = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.FieldStat").msgclass
    TypeStat = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.TypeStat").msgclass
    StatsPerSignature = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.StatsPerSignature").msgclass
    TracesReport = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.TracesReport").msgclass
    Field = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.Field").msgclass
    Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.Type").msgclass
    StatsReport = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.StatsReport").msgclass
    SchemaReport = Google::Protobuf::DescriptorPool.generated_pool.lookup("optics_agent.proto.SchemaReport").msgclass
  end
end
